sequenceDiagram
	autonumber
	participant browser as User/<br>Browser extension
	participant noa as NuNet orchestrator <br> on machine 0
	participant machine1 as Machine 1
	participant machine2 as Machine 2
	participant service1 as SNet AI service 1
	participant service2 as SNet AI service 2

	browser ->> noa: Control: initiate workflow<br>Data: [workflow-definition.json, text to check for fake-news];
	noa ->> service1: Control: request to do work
	noa ->> service2: Control: request to do work
	service1 ->> noa: Control: request accepted, Data: [service1-metadata.json];
	service2 ->> noa: Control: request accepted, Data: [service2-metadata.json];
	noa ->> machine1: Control: request for deployment
	noa ->> machine2: Control: request for deployment
	machine1 ->> noa: Control: request accepted, Data [machine1-metadata.json];
	machine2 ->> noa: Control: request accepted, Data [machine2-metadata.json];
	noa ->> noa: Workflow construction and verification
	noa ->> machine1: Control: deploy SNet AI service 1
	noa ->> machine2: Control: deploy SNet AI service 2
	noa ->> service1: Control: initiate work, Data: [text to check for fake-news]	
	noa ->> service2: Control: initiate work, Data: [text to check for fake-news]	
	service1 ->> noa: Control: work finished, Data: [results 1]
	service2 ->> noa: Control: work finished, Data: [results 2]
	noa ->> noa: Check and combine results
	noa ->> browser: Control: workflow completed, Data: [probability that test contains fake-news]
